apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: manager
  name: manager-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: manager
    spec:
      containers:
      - image: crypto_ml:latest
        name: manager
        imagePullPolicy: Never
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
        command: ["/bin/sh", "-c"]
        args: ["touch newfile && tail -f newfile"]
